dist: trusty
language: python
python:
  - "3.5"

cache: pip

sudo: required

services:
  - docker

notifications:
  webhooks: https://www.travisbuddy.com/

script:
  - docker-compose up &
  - cd python-lib
  - pip install -r requirements.txt
  - python -m unittest test_bassa.py
